### ISSUE TITLE
Interested in collaborating?

### ISSUE THREAD

**Issue by lewinfox** [DominikRafacz/abandonement-flavoured-icecream#1]
Hey! Looks like you and I had the same idea: https://github.com/lewinfox/icecream :) 

I've had a browse through your code - nice work! Wish I knew that `rlang::trace_back()` existed before I started mine... 

What are your plans for the package? Were you planning to submit to CRAN? I was thinking I might do that with mine once I'm happy with it, but it seems silly to have two versions of the same package so I thought I would get in touch. It looks like I have a few more features at this point, but your code is cleaner.

Would you be interested in collaborating? Drop me an email on lewin.a.f <at> gmail.com if you like.

All the best, Lewin

**Comment by DominikRafacz** [comment]
Hi!
Thanks for getting in touch! I will reply in an email 
Greetings!
